version: "3.4"
services:
  s_masstransit_rabbitmq: 
    container_name: "c_masstransit_rabbitmq"
    image: masstransit/rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672

  #s_rabbitmq: 
  #  container_name: "c_rabbitmq"
  #  image: rabbitmq:3-management
  #  ports: 
  #    - 5672:5672
  #    - 15672:15672

  s_redis: 
    container_name: "c_redis"
    image: redis
    ports: 
      - 6379:6379

volumes:
  rabbitmq: